CREATE TABLE test1 (
	id INT NOT NULL GENERATED ALWAYS AS IDENTITY,
	message VARCHAR(24),
	PRIMARY KEY (id)
);

CREATE TABLE test2 (
	id INT NOT NULL GENERATED ALWAYS AS IDENTITY,
	message VARCHAR(24),
	PRIMARY KEY (id)
);
